$$
\newcommand{\ket}[1]{\left|{#1}\right\rangle}
\newcommand{\bra}[1]{\left\langle{#1}\right|}
\newcommand{\braket}[1]{\langle | {#1} | \rangle}
$$

# Estado puro de sistema bipartido


Vimos em aula que um sistema com $N$ qubits em um estado puro é, em geral, descrito como uma superposição de todas as $2^N$ possíveis configurações de $0$'s e $1$'. 

Por exemplo, 
- dois qubits têm $2^2 = 4$ configurações :

$$
\begin{align*} |\Psi\rangle & =
  \alpha_{00} |00\rangle 
+ \alpha_{01} |01 \rangle 
+ \alpha_{10} |10\rangle
+ \alpha_{11} |11\rangle 
\end{align*}$$


<br>

- três qubits têm $2^3 = 8$ configurações: 

$$
\begin{align*} |\Psi\rangle & =
  \alpha_{000} |000\rangle 
+ \alpha_{001} |001 \rangle 
+ \alpha_{010} |010\rangle
+ \alpha_{011} |011\rangle 
+ \alpha_{101} |101\rangle 
+ \alpha_{110} |110\rangle 
+ \alpha_{111} |111\rangle 
\end{align*}$$

<br>


- quadro qubits têm $2^4= 16$ configurações:

$$
\begin{align*} |\Psi\rangle & =
  \alpha_{0000} |0000\rangle 
+ \alpha_{0001} |0001 \rangle 
+ \alpha_{0010} |0010\rangle + ... + 
+ \alpha_{1111} |0011\rangle
\end{align*}$$


## Bases de qubits

Para gerar a base $\{ | \sigma_1 \sigma_2 ... \sigma_N \rangle \}$  com esses $2^N$ configurações, fazemos o produto tensorial entre os estados da base individual de cada qubit $\{ | \sigma_j \rangle \}$ onde $\sigma_j = 0,1$. Isto é:

$$
\begin{align*}
\{ | \sigma_1 \sigma_2 ... \sigma_N \rangle \} = 
\begin{pmatrix}
|\sigma_0\rangle =\begin{pmatrix} 1 \\ 0   \end{pmatrix} \\
|\sigma_1\rangle = \begin{pmatrix} 0 \\ 1 \end{pmatrix} \\
\end{pmatrix}_{n=1} 
\otimes 
\begin{pmatrix}
|\sigma_0\rangle =\begin{pmatrix} 1 \\ 0   \end{pmatrix} \\
|\sigma_1\rangle = \begin{pmatrix} 0 \\ 1 \end{pmatrix} \\
\end{pmatrix}_{n=2} \otimes \dots \otimes
\begin{pmatrix}
|\sigma_0\rangle =\begin{pmatrix} 1 \\ 0   \end{pmatrix} \\
|\sigma_1\rangle = \begin{pmatrix} 0 \\ 1 \end{pmatrix} \\
\end{pmatrix}_{n=N} 
\end{align*}
$$

Abaixo, vamos fazer uma função que gera todas essas configurações para $N$ qubits usando o numpy. 
Para isso, podemos usar o fato de que para cada configuração binária equivale a um índice $j=0, ..., 2^N-1$. 
No exemplo de de três qubits
$$
\begin{align*}
j =0 \rightarrow|000\rangle\\
j =1 \rightarrow|001\rangle\\
j =2 \rightarrow|010\rangle\\
j =3 \rightarrow|011\rangle\\
j =4 \rightarrow|100\rangle\\
j =5 \rightarrow|101\rangle\\
j =6 \rightarrow|110\rangle\\
j =7 \rightarrow|111\rangle\\
\end{align*}
$$

Fatoramos esse índice em potências de $2^n$ com $n=0, ..., N-1$. Por exemplo, para $N=3$ 

$$\begin{align*}
j =0 \rightarrow 0 \times 2^2 + 0 \times 2^1 + 0 \times 2^0
\\
j =1 \rightarrow 0 \times 2^2 + 0 \times 2^1 + 1 \times 2^0
\\
j =2 \rightarrow 0 \times 2^2 + 1 \times 2^1 + 0 \times 2^0
\\
j =3 \rightarrow 0 \times 2^2 + 1 \times 2^1 + 1 \times 2^0
\\
j =4 \rightarrow 1 \times 2^2 + 0 \times 2^1 + 0 \times 2^0
\\
j =5 \rightarrow 1 \times 2^2 + 0 \times 2^1 + 1 \times 2^0
\\
j =6 \rightarrow 1 \times 2^2 + 1 \times 2^1 + 0 \times 2^0
\\
j =7 \rightarrow 1 \times 2^2 + 1 \times 2^1 + 1 \times 2^0
\end{align*}
$$

O dígito ($0$ ou $1$) que acompanha a potência de $2^n$ nada mais é do que o resultado da divisão do índice por 2 e ele dá exatamente a configuração na ordem que queremos. 



<b>Uma observação</b>: por causa da memória, o máximo $N$ razoável para adotarmos é da ordem de $N=16$. A partir desse tamanho, o computador começa a ter dificuldades ...




In [1]:

import numpy as np

In [2]:
def index_to_binary(index : int, N : int):
    '''
    Function converts integer index to binary configuration factorizing it.
    
    Inputs:
    - index: index to be factorized
    - N: number of qubits
    
    Outputs:
    - binstate: np.array with the corresponding binary configuration
    
    
    '''
    if(index > 2**N):
        raise ValueError(f'Configuration does not exist for N ={N} sites')

    if(N > 18):
        raise ValueError(f'Careful with system size. Max N=16!')

    
    binstate = np.zeros((N), dtype=int)

    for i in range(N):
        digit = index / int(2**i) % 2
        binstate[N-i-1] = digit

    return binstate

def binary_configurations(N: int):
    if(N > 18):
        raise ValueError(f'Careful with system size. Max N=16!')
        
    D = int(2**N)
    binary_basis = np.zeros((D,N), dtype=int)
    for j in range(D):
        binary_basis[j,:] = index_to_binary(j,N).T
        
    return binary_basis
    

Vamos ver a seguir alguns casos



In [3]:
for N in range(2,18):

    basis_Nqubits = binary_configurations(N)
    print(f'\n {N} qubits:\n', basis_Nqubits)




 2 qubits:
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]

 3 qubits:
 [[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]

 4 qubits:
 [[0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]
 [0 1 0 1]
 [0 1 1 0]
 [0 1 1 1]
 [1 0 0 0]
 [1 0 0 1]
 [1 0 1 0]
 [1 0 1 1]
 [1 1 0 0]
 [1 1 0 1]
 [1 1 1 0]
 [1 1 1 1]]

 5 qubits:
 [[0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 1 0]
 [0 0 0 1 1]
 [0 0 1 0 0]
 [0 0 1 0 1]
 [0 0 1 1 0]
 [0 0 1 1 1]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 1 0 1 0]
 [0 1 0 1 1]
 [0 1 1 0 0]
 [0 1 1 0 1]
 [0 1 1 1 0]
 [0 1 1 1 1]
 [1 0 0 0 0]
 [1 0 0 0 1]
 [1 0 0 1 0]
 [1 0 0 1 1]
 [1 0 1 0 0]
 [1 0 1 0 1]
 [1 0 1 1 0]
 [1 0 1 1 1]
 [1 1 0 0 0]
 [1 1 0 0 1]
 [1 1 0 1 0]
 [1 1 0 1 1]
 [1 1 1 0 0]
 [1 1 1 0 1]
 [1 1 1 1 0]
 [1 1 1 1 1]]

 6 qubits:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 1 1]
 [0 0 0 1 0 0]
 [0 0 0 1 0 1]
 [0 0 0 1 1 0]
 [0 0 0 1 1 1]
 [0 0 1 0 0 0]
 [0 0 1 0 0 1]
 [0 0 1 0 1 0]
 [0 0 1 0 1 1]
 [0 0 1 1 0 0]
 [0 0 1 1 0 1]
 [0 0 1 1 1 0]
 [0 0 1 1 1 1]

# Estados produto

Vimos que estados produtos que permitem escrever a função de onda em termos dos estados individuais das partes do sistema.

$$
|\Psi\rangle = |\psi_1\rangle \otimes |\psi_2\rangle \otimes ... \otimes ... |\psi_N\rangle 
$$

E isso traz uma vantagem enorme porque:
- toda a informação sobre o sistema pode ser obtida em termos de $D = Nd $ coeficientes ($d$ sendo a dimensão dos espaços de Hilbert onde $| \psi_n \rangle$ é definido), que é um número bem menor do que o caso geral que cresce exponencialmente com o tamanho $D = d^N $.
- observáveis locais da parte $n$ só dependem de $|\psi_n\rangle$: $\langle \hat{O}_n\rangle = \langle \psi_n | \hat{O}_n|\psi_n \rangle $


## Qubits
No caso de qubits, invés de $2^N$ teremos $2N$ coeficiences. Para $N=4$ essa redução já é apreciável: de $256$ para $16$.

Para $2$ qubits $a$ e $B$ nos estados $ |\psi_{A}\rangle = \alpha_0^A |0\rangle + \alpha_1^A |1\rangle$ e 
$ |\psi_{B}\rangle = \alpha_0^B |0\rangle + \alpha_1^B |1\rangle$, o estado composto será


$$
\begin{align*}
|\Psi_{AB}\rangle & = 
\begin{pmatrix} 
\alpha_0^A \\
\alpha_1^A
\end{pmatrix} \otimes 
\begin{pmatrix} 
\alpha_0^B \\
\alpha_1^B
\end{pmatrix} & = 
\begin{pmatrix} 
\alpha_0^A \alpha_0^B \\
\alpha_0^A \alpha_1^B \\
\alpha_1^A \alpha_0^B \\ 
\alpha_1^A \alpha_1^B
\end{pmatrix}
\end{align*}
$$


Para implementar o estado produto numericamente usando o numpy diretamente através da função 
```python 
np.kron(psi_A,psi_B)
```


No QuTip, se representamos o qubit como Qobj, o produto tensorial é implementado através da função 
```python 
qutip.tensor(psi_A,psi_B)
```



<br>

Vamos considerar os exemplos da aula
$$
\begin{align*}
|\psi_A\rangle &= \begin{pmatrix}
1 \\
0
\end{pmatrix} \quad \quad
|\psi_B\rangle =\begin{pmatrix}
\frac{1}{\sqrt{2}} \\
-\frac{1}{\sqrt{2}}
\end{pmatrix}
\end{align*}
$$

In [4]:
# exemplo numpy

psi_A = np.array([0,1]).reshape(2,1)
psi_B = 1./np.sqrt(2) * np.array([1,-1]).reshape(2,1)

Psi_AB = np.kron(psi_A, psi_B)
print(f'|Psi_AB> = \n', Psi_AB)

|Psi_AB> = 
 [[ 0.        ]
 [-0.        ]
 [ 0.70710678]
 [-0.70710678]]


In [5]:
# exemplo qutip
import qutip
zero = qutip.basis(2,0)
one = qutip.basis(2,1)

psi_A = one
psi_B = 1./np.sqrt(2) * (zero - one)
Psi_AB = qutip.tensor(psi_A, psi_B)
print(f'|Psi_AB> = \n', Psi_AB)

|Psi_AB> = 
 Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [ 0.        ]
 [ 0.70710678]
 [-0.70710678]]


# Estado emaranhado


Estados que não podem ser escritos como produto são emaranhados! 
$$
|\Psi\rangle \neq |\psi_1\rangle \otimes |\psi_2\rangle \otimes ... \otimes |\psi_N\rangle
$$

Um exemplo para dois qubits $A$ e $B$ é 
\begin{align*}
|\Psi_{AB}\rangle & = \frac{1}{\sqrt{2}}(|0_A 0_B\rangle + |1_A 1_B\rangle)\\
& = \frac{1}{\sqrt{2}}(|00\rangle +|11\rangle) \\
& = \frac{1}{\sqrt{2}}\begin{pmatrix}
1 \\ 
0 \\
0 \\
1
\end{pmatrix}
\end{align*}


Vimos que existem $4$ estados maximamente emaranhados para $2$ qubits que compõe a base de Bell. O QuTip tem essa base prontinha para ser usada. E ele usa a seguinte notação 
```python 
qutip.bell_state(state='00')
```

onde a string que aparece para definir o estado segue a seguinte notação:

$$
\begin{align*}
\ket{B_{00}} = \ket{\Phi^+} & = \frac{1}{\sqrt{2}}(\ket{00} + \ket{11})\\
\ket{B_{01}} = \ket{\Phi^-} & = \frac{1}{\sqrt{2}}(\ket{00} - \ket{11})\\
\ket{B_{10}} = \ket{\Psi^+} & = \frac{1}{\sqrt{2}}(\ket{01} + \ket{10})\\
\ket{B_{11}}= \ket{\Psi^-} & = \frac{1}{\sqrt{2}}(\ket{01} - \ket{01})
\end{align*}
$$




In [6]:
Phi_p = qutip.bell_state('00')
print('\n B_00')
Phi_p


 B_00


Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]

In [7]:
Phi_m = qutip.bell_state('01')
print('\n B_01')
Phi_m


 B_01


Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.70710678]
 [ 0.        ]
 [ 0.        ]
 [-0.70710678]]

In [8]:
Psi_p = qutip.bell_state('10')
print('\n B_10 ')
Psi_p


 B_10 


Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]

In [9]:
Psi_m = qutip.bell_state('11')
print('\n B_11 ')
Psi_m


 B_11 


Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [ 0.70710678]
 [-0.70710678]
 [ 0.        ]]

# Medidas conjuntas e separadas
Vamos agora fazer uma medida de $\hat{\sigma}_z$ em cada um dos qubits e ver a diferença entre fazer as medidas uma seguida da outra ou uma medida conjunta. 

Consideremos que ao medir através de $\hat{P}$, a função de onda colapsa
$$
\ket{\Psi'} = \frac{\hat{P} \ket{\psi}}{\sqrt{\Psi|\hat{P}|\Psi}}
.$$


## Exemplo: dois qubits em estados produto ou emaranhados


Vimos que em estados emaranhados, ganha-se mais informação fazendo medidas separadas. 

Vamos, então considerar dois exemplos de estados para dois qubits $A$ e $B$ em que eles estão em estados produto ou estados emaranhados.

No primeiro caso, tomemos o estado do qubit $A$ como $\ket{0_A}$ e o estado do qubit $B$ como $\ket{+_B} = \frac{1}{\sqrt{2}} (\ket{0_B} + \ket{1}_B)$. No segundo caso, teremos os qubits como o estado singleto $\ket{\Psi^-}$ da base de Bell.



Para medir $\hat{\sigma}_z^A$ ou $\hat{\sigma}_z^B$ separadamente usamos os operadores

$$
\hat{Z}_A = \hat{\sigma}_z^A \otimes \mathbb{I}_B
$$

$$
\hat{Z}_B = \mathbb{I}_B \otimes \hat{\sigma}_z^B
$$


Para fazer a medida conjunta 

$$
\hat{Z}_{AB} = \hat{\sigma}_z^A \otimes \hat{\sigma}_z^B
$$


Veja que as medidas podem ter resultado $+1$ ou $-1$. Medindo várias vezes saberemos a probabilidade de obter cada um desses resultados, bem como o estado para o qual a função de onda vai colapsar. 


<br>

O QuTip têm funções permitindo fazer a medida e obter os possíveis valores bem como estados colapsados. As funções ficam no módulo measurement.  A sintaxe é

```python

outcomes_measurement, collapsed_states, probabilities = qutip.measurement.measurement_statistics(state_operator, measurement_operator)
```






In [10]:
# o unit serve para normalizar a função
plus = (zero+one).unit()

In [11]:
# estado produto
Psi_AB_produto = qutip.tensor(zero, plus)
print('AB produto')
Psi_AB_produto

AB produto


Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]
 [0.        ]
 [0.        ]]

In [12]:
# estado emaranhado 
Psi_AB_emaranhado = Psi_m
print('AB emaranhado')
Psi_AB_emaranhado 

AB emaranhado


Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [ 0.70710678]
 [-0.70710678]
 [ 0.        ]]

In [13]:
# medidas individuais
Z_A = qutip.tensor(qutip.sigmaz(), qutip.qeye(2))
Z_B = qutip.tensor(qutip.qeye(2), qutip.sigmaz())

# medidas conjuntas
Z_AB = qutip.tensor(qutip.sigmaz(), qutip.sigmaz())


In [14]:
# estado produto 
# fazendo as medidas separadas 
ZA_outcomesP, ZA_collapsedP, ZA_probabilitiesP = qutip.measurement.measurement_statistics_observable(Psi_AB_produto, Z_A)
ZB_outcomesP, ZB_collapsedP, ZB_probabilitiesP = qutip.measurement.measurement_statistics_observable(Psi_AB_produto, Z_B)

# fazendo a medida conjunta 
ZAB_outcomesP, ZAB_collapsedP, ZAB_probabilitiesP = qutip.measurement.measurement_statistics_observable(Psi_AB_produto, Z_AB)


In [15]:
print('estado produto')
print('\n qubit A')

print('outcomes', ZA_outcomesP)
print('probabilidades', ZA_probabilitiesP)
for ia, za in enumerate(ZA_outcomesP):
    print(f'\n medida = {za}, probabilidade = {ZA_probabilitiesP[ia]}')
    print('estado colapsado = ', ZA_collapsedP[ia].full())


print('\n qubit B \n')
print('outcomes', ZB_outcomesP)
print('probabilidades', ZB_probabilitiesP)
for ib, zb in enumerate(ZB_outcomesP):
    print(f'\n medida = {zb}, probabilidade = {ZB_probabilitiesP[ib]}')
    print('estado colapsado = ', ZB_collapsedP[ib].full())


print('\n qubits AB \n')
print('outcomes', ZAB_outcomesP)
print('probabilidades', ZAB_probabilitiesP)
for iab, zab in enumerate(ZAB_outcomesP):
    print(f'\n medida = {zab}, probabilidade = {ZAB_probabilitiesP[iab]}')
    print('estado colapsado = ', ZAB_collapsedP[iab].full())


estado produto

 qubit A
outcomes [-1. -1.  1.  1.]
probabilidades [0, 0, 0.4999999999999999, 0.4999999999999999]

 medida = -1.0, probabilidade = 0
estado colapsado =  [[0.+0.j]
 [0.+0.j]
 [1.+0.j]
 [0.+0.j]]

 medida = -1.0, probabilidade = 0
estado colapsado =  [[0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [1.+0.j]]

 medida = 1.0, probabilidade = 0.4999999999999999
estado colapsado =  [[1.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]]

 medida = 1.0, probabilidade = 0.4999999999999999
estado colapsado =  [[0.+0.j]
 [1.+0.j]
 [0.+0.j]
 [0.+0.j]]

 qubit B 

outcomes [-1. -1.  1.  1.]
probabilidades [0.4999999999999999, 0, 0.4999999999999999, 0]

 medida = -1.0, probabilidade = 0.4999999999999999
estado colapsado =  [[0.+0.j]
 [1.+0.j]
 [0.+0.j]
 [0.+0.j]]

 medida = -1.0, probabilidade = 0
estado colapsado =  [[0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [1.+0.j]]

 medida = 1.0, probabilidade = 0.4999999999999999
estado colapsado =  [[1.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]]

 medida = 1.0, probabilidade = 0
estado colapsa

In [16]:
# estado emaranhado
# fazendo as medidas separadas 
ZA_outcomesE, ZA_collapsedE, ZA_probabilitiesE = qutip.measurement.measurement_statistics_observable(Psi_AB_emaranhado, Z_A)
ZB_outcomesE, ZB_collapsedE, ZB_probabilitiesE = qutip.measurement.measurement_statistics_observable(Psi_AB_emaranhado, Z_B)

# fazendo a medida conjunta 
ZAB_outcomesE, ZAB_collapsedE, ZAB_probabilitiesE = qutip.measurement.measurement_statistics_observable(Psi_AB_emaranhado, Z_AB)


In [17]:
print('estado emaranhado')
print('\n qubit A')

print('outcomes', ZA_outcomesE)
print('probabilidades', ZA_probabilitiesE)
for ia, za in enumerate(ZA_outcomesE):
    print(f'\n medida = {za}, probabilidade = {ZA_probabilitiesE[ia]}')
    print('estado colapsado = ', ZA_collapsedE[ia].full())


print('\n qubit B \n')
print('outcomes', ZB_outcomesE)
print('probabilidades', ZB_probabilitiesE)
for ib, zb in enumerate(ZB_outcomesE):
    print(f'\n medida = {zb}, probabilidade = {ZB_probabilitiesE[ib]}')
    print('estado colapsado = ', ZB_collapsedE[ib].full())


print('\n qubits AB \n')
print('outcomes', ZAB_outcomesE)
print('probabilidades', ZAB_probabilitiesE)
for iab, zab in enumerate(ZAB_outcomesE):
    print(f'\n medida = {zab}, probabilidade = {ZAB_probabilitiesE[iab]}')
    print('estado colapsado = ', ZAB_collapsedE[iab].full())


estado emaranhado

 qubit A
outcomes [-1. -1.  1.  1.]
probabilidades [0.4999999999999999, 0, 0, 0.4999999999999999]

 medida = -1.0, probabilidade = 0.4999999999999999
estado colapsado =  [[0.+0.j]
 [0.+0.j]
 [1.+0.j]
 [0.+0.j]]

 medida = -1.0, probabilidade = 0
estado colapsado =  [[0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [1.+0.j]]

 medida = 1.0, probabilidade = 0
estado colapsado =  [[1.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]]

 medida = 1.0, probabilidade = 0.4999999999999999
estado colapsado =  [[0.+0.j]
 [1.+0.j]
 [0.+0.j]
 [0.+0.j]]

 qubit B 

outcomes [-1. -1.  1.  1.]
probabilidades [0.4999999999999999, 0, 0, 0.4999999999999999]

 medida = -1.0, probabilidade = 0.4999999999999999
estado colapsado =  [[0.+0.j]
 [1.+0.j]
 [0.+0.j]
 [0.+0.j]]

 medida = -1.0, probabilidade = 0
estado colapsado =  [[0.+0.j]
 [0.+0.j]
 [0.+0.j]
 [1.+0.j]]

 medida = 1.0, probabilidade = 0
estado colapsado =  [[1.+0.j]
 [0.+0.j]
 [0.+0.j]
 [0.+0.j]]

 medida = 1.0, probabilidade = 0.4999999999999999
estado cola

# Geradores de emaranhamento

Os estados da base de Bell podem ser gerados a partir de duas portas lógicas (ou <i> gates </i>): Hadamard e CNOT.

Esses gates são definidos a seguir. Hadamard é
$$
\begin{align*}\hat{H}_g = \frac{1}{\sqrt{2}}\begin{pmatrix}
1 & 1 \\ 
1 & -1
\end{pmatrix}
\end{align*}
$$

CNOT é
$$
\begin{align*}
\hat{U}_{\text{CNOT}} = \begin{pmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 0 & 1 \\
0 & 0 & 1 & 0
\end{pmatrix}
\end{align*}
$$

O QuTip tem esses gates implementados no submodulo gates. O gate Hadamard é chamado snot. 

```python3 
 from qutip.qip.operations.gates import cnot as gate_CNOT
 from qutip.qip.operations.gates import cnot as gate_Hadamard
 ```


Vimos que partindo de dois qubits inicializados em $\ket{00}$ sempre poderemos construir a base de Bell usando esses dois gates e $\hat{\sigma}_x$ para flipar um dos qubits.


$$
\begin{align*}
\ket{00} & \rightarrow{\quad \hat{H}_A\quad } \frac{1}{\sqrt{2}} (\ket{00}+\ket{10})\rightarrow{\quad  \hat{U}_{\text{CNOT}}  \quad }
 \frac{1}{\sqrt{2}} (\ket{00}+\ket{11}) = \ket{\Phi^+}
\end{align*}
$$

$$
\begin{align*}
\ket{00} & \xrightarrow{\quad \hat{\sigma}_x^B \quad }  \ket{01}\xrightarrow{\quad \hat{H}_A\quad } \frac{1}{\sqrt{2}} (\ket{01}+\ket{11})\xrightarrow{\quad  \hat{U}_{\text{CNOT}}  \quad }
 \frac{1}{\sqrt{2}} (\ket{01}+\ket{10}) = \ket{\Psi^+}
\end{align*}
$$

$$
\begin{align*}
\ket{00} & \xrightarrow{\quad \hat{\sigma}_x^A \quad }  \ket{10}\xrightarrow{\quad \hat{H}_A\quad } \frac{1}{\sqrt{2}} (\ket{00}-\ket{10})\xrightarrow{\quad  \hat{U}_{\text{CNOT}}  \quad }
 \frac{1}{\sqrt{2}} (\ket{00}-\ket{11}) = \ket{\Phi^-}
\end{align*}
$$



$$
\begin{align*}
\ket{00} & \xrightarrow{\quad \hat{\sigma}_x^A \quad }  \ket{10}
\xrightarrow{\quad \hat{\sigma}_x^B \quad }  \ket{11}
\xrightarrow{\quad \hat{H}_A\quad } \frac{1}{\sqrt{2}} (\ket{01}-\ket{11})\xrightarrow{\quad  \hat{U}_{\text{CNOT}}  \quad }
 \frac{1}{\sqrt{2}} (\ket{01}-\ket{10}) = \ket{\Psi^-}
\end{align*}
$$

Vamos fazer essa implementação "classicamente" a seguir.



In [18]:
# importando os gates
from qutip.qip.operations.gates import cnot as gate_CNOT
gate_CNOT()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [19]:
from qutip.qip.operations.gates import snot as gate_Hadamard
gate_Hadamard()

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

In [20]:
# inicializando os qubits em 00

qinit_AB = qutip.tensor(zero,zero)
qinit_AB

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[1.]
 [0.]
 [0.]
 [0.]]

In [21]:
# local Hadamard em A
H_A = qutip.tensor(gate_Hadamard(), qutip.qeye(2))
H_A



Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[ 0.70710678  0.          0.70710678  0.        ]
 [ 0.          0.70710678  0.          0.70710678]
 [ 0.70710678  0.         -0.70710678  0.        ]
 [ 0.          0.70710678  0.         -0.70710678]]

In [24]:
# local sx em A
X_A = qutip.tensor(qutip.sigmax(), qutip.qeye(2))
X_A

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]

In [28]:
# local sx em B
X_B = qutip.tensor(qutip.qeye(2), qutip.sigmax())
X_B

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]

In [22]:
Bg_00 = gate_CNOT() * H_A * qinit_AB
Bg_00

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]

In [29]:
Bg_01 = gate_CNOT() * H_A * X_B * qinit_AB
Bg_01

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]

In [30]:
Bg_10 = gate_CNOT() * H_A * X_B * X_A * qinit_AB
Bg_10

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [ 0.70710678]
 [-0.70710678]
 [ 0.        ]]

In [31]:
Bg_11 = gate_CNOT() * H_A * X_A * qinit_AB
Bg_11

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.70710678]
 [ 0.        ]
 [ 0.        ]
 [-0.70710678]]

## Emaranhamento por dinâmica

O operador $\hat{Z}_{AB}$ que pode ser usado como uma medida para saber se os estados dos qubits coincidem, quando visto como interação é, na verdade, um gerador de emaranhamento. 

Para apreciar este fato, podemos tomar como exemplo dois qubits  inicializados em um estado produto

$$ \ket{\Psi}_{AB} = \ket{\psi_A} \otimes \ket{\psi_B}$$

ortonal a qualquer um dos estados da base de Bell e evoluí-lo através do Hamiltoniano 

$$\hat{H} = \frac{\omega_A}{2} \hat{\sigma}_A 
+ \frac{\omega_B}{2} \hat{\sigma}_B +
+  g \hat{\sigma}_z^B \otimes \hat{\sigma}_B
$$

e medirmos a projeção do estado evoluído na base de Bell. 