# Exemplos para o operador densidade

## Sistema de dois níveis

Vamos definir os estados fundamental $$|0\rangle = \begin{pmatrix} 1 \\ 0\end{pmatrix}$$ e excitado $$|1\rangle = \begin{pmatrix} 0 \\ 1\end{pmatrix}$$


In [1]:
# numpy, a biblioteca útil para operações com vetores e matrizes
import numpy as np

zero = np.array([1,0]).reshape(2,1)
one = np.array([0,1]).reshape(2,1)

### Mistura de estados puros sem transições

Consideremos primeiro uma mistura sem transições com peso $1-\epsilon$ para o fundamental e $\epsilon$ para o excitado:

$$\hat{\rho} = (1-\epsilon) | 0 \rangle \langle 0| + \epsilon | 1 \rangle \langle 1|$$

Com o numpy, para dois estados $| a \rangle$ e $| b \rangle$ que são numpy arrays, construir o ket-bra $| a \rangle \langle b |$ é fácil usando o np.outer(a,b.conjugate()). Note que precisamos o vetor que vem no bra!

In [14]:
epsilon = 0.1
rho1 = (1 - epsilon) * np.outer(zero, zero.conjugate()) + epsilon * np.outer(one, one.conjugate())

# matrix abaixo
print('rho:\n', rho1)

rho:
 [[0.9 0. ]
 [0.  0.1]]


### Estado puro que é combinação 

Consideremos a combinação $| 0 \rangle$ e $| 1 \rangle$ com probabilidades $(1-\epsilon)$ e $\epsilon$
$$ | \psi\rangle = \sqrt{1-\epsilon}| 0 \rangle + \sqrt{\epsilon} | 1 \rangle$$


In [15]:
psi1 = np.sqrt(1-epsilon) * zero + np.sqrt(epsilon) * one

# estado 
print('psi:\n', psi1)

psi:
 [[0.9486833 ]
 [0.31622777]]


Seja $$\hat{\rho} = | \psi \rangle \langle \psi|$$

In [12]:
rho2 = np.outer(psi1, psi1.conjugate())
print('produto: \n', rho2)
# compare com 
rho2b = np.array([[1-epsilon, np.sqrt(epsilon*(1-epsilon))],[np.sqrt(epsilon*(1-epsilon)), epsilon]])
print('na mao:\n', rho2b)

produto: 
 [[0.9 0.3]
 [0.3 0.1]]
na mao:
 [[0.9 0.3]
 [0.3 0.1]]


### Auto-estados de $\hat{\sigma}_x$
Vamos definir o operador 

$$ \hat{\sigma}_x = \begin{pmatrix} 0 & 1 \\ 1 & 0\end{pmatrix}$$

In [21]:
sigma_x = np.array([[0,1],[1,0]])
print('sx: \n', sigma_x)

sx: 
 [[0 1]
 [1 0]]


Agora mostrar que os auto-estados são os $ |+ \rangle$ e $ |- \rangle$ com autovalores $+1$ e $-1$, respectivamente. No numpy, a função np.linalg.eigh serve para diagonalizar matrizes Hermitianas, caso do operador em questão.



In [23]:
vals_sx, vets_sx = np.linalg.eigh(sigma_x)
print('autovalores: \n', vals_sx)

print('\n auto vetores (em colunas): \n', vets_sx)

autovalores: 
 [-1.  1.]

 auto vetores (em colunas): 
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


As vezes o sinal de um autovetor vem trocado, mas tudo bem. Eles continuam ortonormais e não vão mudar nosso resultado.


In [64]:
minus = vets_sx[:,0].reshape(2,1)
# eu vou trocar o sinal por consistência
plus = -vets_sx[:,1].reshape(2,1)

Agora, vamos construir um operador que é uma mistura desses estados com probabilidades 50% pra cada

$$\hat{\rho} = \frac{1}{2} | + \rangle \langle +| +\frac{1}{2} | - \rangle \langle -|$$


In [65]:
rhopm = 0.5 * np.outer(plus, plus.conjugate()) + 0.5 * np.outer(minus, minus.conjugate())

print('rho_pm: \n', rhopm)

rho_pm: 
 [[0.5 0. ]
 [0.  0.5]]


Lembrando que é a mesma matriz que teríamos se trocássemos de volta pra 0 e 1

In [66]:
rho01 = 0.5 * np.outer(one, one.conjugate()) + 0.5 * np.outer(zero, zero.conjugate())

print('rho_01: \n', rho01)

rho_01: 
 [[0.5 0. ]
 [0.  0.5]]


Agora, vamos ver o caso de uma matriz de densidade construída a partir de um estado puro $| \psi_\pm \rangle$ uma combinação dos $ |+ \rangle$ e $ |- \rangle$ 

$$ | \psi_{\pm}\rangle = \sqrt{1-\epsilon}| + \rangle + \sqrt{\epsilon} | - \rangle$$

In [67]:
psi_pm = np.sqrt(1-epsilon) * plus + np.sqrt(epsilon) * minus
print('psi_pm:\n', psi_pm)

rho_psipm = np.outer(psi_pm, psi_pm.conjugate())
print('rho_psipm:\n', rho_psipm)

psi_pm:
 [[-0.89442719]
 [-0.4472136 ]]
rho_psipm:
 [[0.8 0.4]
 [0.4 0.2]]


A mesma matriz na base  $ |+ \rangle$ e $ |- \rangle$  é 

$$
\hat{\rho}_{+-} = \begin{pmatrix} 1 -\epsilon & \sqrt{\epsilon(1-\epsilon)} \\ \sqrt{\epsilon(1-\epsilon)}  & \epsilon\end{pmatrix}
$$

In [68]:
rho_pm = np.array([[1-epsilon, np.sqrt(epsilon*(1-epsilon))],[np.sqrt(epsilon*(1-epsilon)), epsilon]])
                   
print('rho_pm: \n', rho_pm)

rho_pm: 
 [[0.9 0.3]
 [0.3 0.1]]


Vamos rodar as bases usando 

$$
    \hat{\rho}_{10} = \hat{U}_{\pm, 01}^\dagger \hat{\rho}_{+-}\hat{U}_{\pm, 01}
$$

A matrix $$  \hat{U}_{\pm, 01}$$ roda o sistema de $+-$ para $01$. Ela nada mais é do que a matriz de autovetores de $\hat{\sigma}_x$! Ou, explicitamente 

$$  \hat{U}_{\pm, 01} = \left( |+\rangle \quad |-\rangle \right)$$

In [69]:
# estou usando copy porque o python, as vezes, usa um ponteiro na atribuicao do = e pode dar ruim se mudar a variável depois
U_pm_01 = np.copy(vets_sx)
# aqui eu vou mudar o sinal do vetor por consistência
U_pm_01[:,0] *= -1
print('U_pm_01: \n', U_pm_01)


U_pm_01: 
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [70]:
print('rodando: \n', U_pm_01.T.conjugate() @ rho_pm @ U_pm_01)
print('\nrho_psipm:\n', rho_psipm)

rodando: 
 [[0.2 0.4]
 [0.4 0.8]]

rho_psipm:
 [[0.8 0.4]
 [0.4 0.2]]


In [72]:
# ou, iterativamente
rho_01_aux_diag = (1-epsilon)*np.outer(plus, plus)+epsilon*np.outer(minus, minus)
print('rho_01 parte |+><+| e |-><-|: \n', rho_01_aux_diag)

rho_01_aux_offdiag= np.sqrt(epsilon*(1-epsilon))*(np.outer(plus, minus)+np.outer(minus, plus))

print('\n rho_01 parte |-><+| e |+><-|: \n', rho_01_aux_offdiag)

print('\n somando: \n', rho_01_aux_diag + rho_01_aux_offdiag)

rho_01 parte |+><+| e |-><-|: 
 [[0.5 0.4]
 [0.4 0.5]]

 rho_01 parte |-><+| e |+><-|: 
 [[ 0.3  0. ]
 [ 0.  -0.3]]

 somando: 
 [[0.8 0.4]
 [0.4 0.2]]


## Pureza

Vimos que a pureza de um estado $\hat{\rho}$ é calculada a partir de seus auto-valores $\lambda_k$ como 

$$
\frac{1}{D}\leq P = \sum_k \lambda_k^2 \leq 1
$$
onde $D$ é a dimensão do espaço de Hilbert no qual $\hat{\rho}$ está definido. 

Vamos calcular a pureza para os estados anteriores. Lembra do estado $ | \psi_{\pm}\rangle = \sqrt{1-\epsilon}| + \rangle + \sqrt{\epsilon} | - \rangle$. Construímos uma matriz de densidade para ele. A pureza dela é, obviamente $1$. Vejamos:


In [83]:

lambdak_01, vlk_01 = np.linalg.eigh(rho_psipm)
print('autovalores de rho_psipm:\n', lambdak_01)
print('\n soma: ', lambdak_01.sum())

autovalores de rho_psipm:
 [0. 1.]

 soma:  0.9999999999999997


Veja que a matriz $\hat{\rho}_{+-}$ (em outra base) não era diagonal e não era igual a ela. Vamos ver que ela tem os mesmos autovalores e auto-vetores.


In [80]:
lambdak_pm, vlk_pm = np.linalg.eigh(rho_pm)
print('autovalores de rho_pm:\n', lambdak_pm)
print('\n soma: ', lambdak_pm.sum())

autovalores de rho_pm:
 [-1.38777878e-17  1.00000000e+00]

 soma:  1.0


Ah, uma coisa, lembra que dissemos que a matriz de densidade é sempre positiva e os autovalores são sempre 
$$\lambda_k \geq 0$$
e somados dão $1$.

OBS: Esse valor muuuuito pequeno aí em cima é negativo. A outra soma deu perto de $1$. Numericamente, isso pode acontecer ...Mas, atente que se aparece algum valor negativo considerável ou a soma muito distante de um pode ter algo estranho. 

Vamos comparar os auto-vetores das duas matrizes. Eles devem ser diferentes mesmo.

In [82]:
print('autovalores de rho_psipm:\n', vlk_01)
print('autovetores de rho_pm:\n', vlk_pm)

autovalores de rho_psipm:
 [[ 0.4472136  -0.89442719]
 [-0.89442719 -0.4472136 ]]
autovetores de rho_pm:
 [[ 0.31622777 -0.9486833 ]
 [-0.9486833  -0.31622777]]


## Estado térmico

Agora vamos falar de estados térmicos que são exemplos de estados não-puros. 
Vimos que um estado térmico a temperatura inversa $\beta$ e definida por um Hamiltoniano $\hat{H}$ pode ser calculado de duas formas.

$$
\hat{\rho}_\beta = \frac{1}{Z}\sum_n e^{-\beta E_n}|\psi_n\rangle \langle\psi_n|
$$
ou
$$
\hat{\rho}_\beta = \frac{e^{-\beta \hat{H}}}{\text{Tr}[e^{-\beta \hat{H}}]}
$$

Vamos considerar os dois Hamiltonianos da aula 
$$\hat{H}_z = -h \hat{\sigma}_z$$ e
$$\hat{H}_x = J \hat{\sigma}_x$$

Tomemos $h=1$ e $J=0.5$

In [86]:
sigma_z = np.array([[1,0],[0,-1]])
print('sz: \n', sigma_z)

vals_sz, vets_sz = np.linalg.eigh(sigma_z)
print('autovalores: \n', vals_sz)

print('\n auto vetores (em colunas): \n', vets_sz)

sz: 
 [[ 1  0]
 [ 0 -1]]
autovalores: 
 [-1.  1.]

 auto vetores (em colunas): 
 [[0. 1.]
 [1. 0.]]


In [89]:
# Hz
h = 1
Hz = -h * sigma_z
print('\n Hz:\n', Hz)

# Hx
J = 0.5
Hx = J * sigma_x
print('\n Hx:\n', Hx)


 Hz:
 [[-1  0]
 [ 0  1]]

 Hx:
 [[0.  0.5]
 [0.5 0. ]]


O $H_z$ já está na forma diagonal, mas os auto-valores estão multiplicados por uma constante negativa. Para facilitar, vamos criar uma função que calcula os pesos de Boltzman e outra que calcula o estado de Gibbs a partir dos autoestados do Hamiltoniano. Alguns hacks são usados para evitar problemas numéricos.


In [144]:
def boltzman_weights(E_n: np.array, beta: float):
    """
    Calculates the Boltzman weights p_n = e^{-beta E_n} / Z, where Z = \sum_n e^{-beta E_n}

    Inputs:
        - E_n: eigenenergies of Hamiltonian, np.array
        - beta: inverse temperature, float
	
	Outputs: 
        - p_n: Boltzman weights (not normalized by the partition function)    
    """
    p_n = np.exp(-(E_n-E_n[0])*beta) / (1.0 + np.exp(-(E_n[1:]-E_n[0])*beta).sum())
    return p_n


def Gibbs_state(E_n: np.array, Psi_n: np.array, beta: float, return_Z=False):
    """
    Calculates the Gibbs state for a system defined by a Hamiltonian $H$ at inverse 
    temperature $\beta = T^{-1}$. 

        $\rho_{Gibbs} = \exp{-\beta H} / Z$

        with $Z = \Tr{\exp{-\beta H}}$.

    In the eigenbasis $\{E_n, \Psi_n\}$ of the Hamiltonian $H$, this state corresponds to
        $\rho_{Gibbs} = \sum_n p_n \ket{\Psi_n} \bra{\Psi_m}$,

    where $p_n = \exp{-\beta E_n} / Z$ are the Boltzman weights.

    Inputs:
        - E_n: eigen-energies of a Hamiltonian (np.array)
        - Psi_n: eigen-states of a Hamiltonian (np.array: matrix)
        - beta: inverse temperature (float)
        - return_Z: flag to return or not the partition function (bool)
	
	Outputs: 
        - rho_Gibbs: density matrix (np.array)
        - Z: partition function (float)    

    """
    D = Psi_n.shape[0]
    rho_Gibbs = np.zeros((D,D))
    p_n = boltzman_weights(E_n, beta)

    for n in range(D):
        rho_Gibbs += p_n[n] * np.outer(Psi_n[:,n], Psi_n[:,n].conjugate())
    
    Z = p_n.sum()

    rho_Gibbs /= Z
    
    if(return_Z is False):
        return rho_Gibbs

    return rho_Gibbs, Z



In [128]:
# energias/autoestados de Hz
En_z = np.array([-h,h])
Psin_z = np.array([zero, one]).reshape(2,2).T

# energias/autoestados de Hx
En_x = np.array([-J,J])
Psin_x = np.array([-minus, plus]).reshape(2,2).T

Podemos calcular os mesmos estados usando a exponenciação dos operadores. Então importamos a função expm scipy.linalg 

In [140]:
from scipy.linalg import expm

In [160]:
# temperatura 0
beta = 200
pn_z_0 = boltzman_weights(En_z, beta)
print('Hz: pesos de Bolztman para T = 0: \n', pn_z_0)
rho_beta_z_0 = Gibbs_state(En_z, Psin_z, beta)
print('Hz: estado térmico T = 0: \n', rho_beta_z_0)
# para esse beta grande, a porca torce o rabo
print('Hz: estado térmico T = 0 (exp H): \n', expm(-beta * Hz) / np.trace(expm(-beta * Hz)))
l_Hz_0 = np.linalg.eigvals(rho_beta_z_0)
print('Hz: pureza T = 0: \n', (l_Hz_0**2).sum())


pn_x_0 = boltzman_weights(En_x, beta)
print('\nHx: pesos de Bolztman para T = 0: \n', pn_x_0)
rho_beta_x_0 = Gibbs_state(En_x, Psin_x, beta)
print('Hx: estado térmico T = 0: \n', rho_beta_x_0)
print('Hx: estado térmico T = 0 (exp H): \n', expm(-beta * Hx) / np.trace(expm(-beta * Hx)))
l_Hx_0 = np.linalg.eigvals(rho_beta_z_0)
print('Hx: pureza T = 0: \n', (l_Hx_0**2).sum())



Hz: pesos de Bolztman para T = 0: 
 [1.0000000e+000 1.9151696e-174]
Hz: estado térmico T = 0: 
 [[1.0000000e+000 0.0000000e+000]
 [0.0000000e+000 1.9151696e-174]]
Hz: estado térmico T = 0 (exp H): 
 [[1. 0.]
 [0. 0.]]
Hz: pureza T = 0: 
 1.0

Hx: pesos de Bolztman para T = 0: 
 [1.00000000e+00 1.38389653e-87]
Hx: estado térmico T = 0: 
 [[ 0.5 -0.5]
 [-0.5  0.5]]
Hx: estado térmico T = 0 (exp H): 
 [[ 0.5 -0.5]
 [-0.5  0.5]]
Hx: pureza T = 0: 
 1.0


In [161]:
# temperatura infinita
beta = 0
pn_z_inf = boltzman_weights(En_z, beta)
print('Hz: pesos de Bolztman para T = inf: \n', pn_z_inf)
rho_beta_z_inf = Gibbs_state(En_z, Psin_z, beta)
print('Hz: estado térmico T = inf: \n', rho_beta_z_inf)
print('Hz: estado térmico T = inf (exp H): \n', expm(-beta * Hz) / np.trace(expm(-beta * Hz)))
l_Hz_inf = np.linalg.eigvals(rho_beta_z_inf)
print('Hz: pureza T = inf: \n', (l_Hz_inf**2).sum())



pn_x_inf = boltzman_weights(En_x, beta)
print('\nHx: pesos de Bolztman para T = inf: \n', pn_x_inf)
rho_beta_x_inf = Gibbs_state(En_x, Psin_x, beta)
print('Hx: estado térmico T = inf: \n', rho_beta_x_inf)
print('Hx: estado térmico T = inf (exp H): \n', expm(-beta * Hx) / np.trace(expm(-beta * Hx)))
l_Hx_inf = np.linalg.eigvals(rho_beta_x_inf)
print('Hx: pureza T = inf: \n', (l_Hx_inf**2).sum())



Hz: pesos de Bolztman para T = inf: 
 [0.5 0.5]
Hz: estado térmico T = inf: 
 [[0.5 0. ]
 [0.  0.5]]
Hz: estado térmico T = inf (exp H): 
 [[0.5 0. ]
 [0.  0.5]]
Hz: pureza T = inf: 
 0.5

Hx: pesos de Bolztman para T = inf: 
 [0.5 0.5]
Hx: estado térmico T = inf: 
 [[0.5 0. ]
 [0.  0.5]]
Hx: estado térmico T = inf (exp H): 
 [[0.5 0. ]
 [0.  0.5]]
Hx: pureza T = inf: 
 0.4999999999999998


In [165]:
# temperatura intermediária 
beta = 0.4
pn_z_b = boltzman_weights(En_z, beta)
print('Hz: pesos de Bolztman para k_B T = 2.5 J: \n', pn_z_b)
rho_beta_z_b = Gibbs_state(En_z, Psin_z, beta)
print('Hz: estado térmico k_B T = 2.5J: \n', rho_beta_z_b)
print('Hz: estado térmico k_B T = 2.5J (exp H): \n', expm(-beta * Hz) / np.trace(expm(-beta * Hz)))
l_Hz_b = np.linalg.eigvals(rho_beta_z_b)
print('Hz: pureza T =  2.5J: \n', (l_Hz_b**2).sum())



pn_x_b = boltzman_weights(En_x, beta)
print('\nHx: pesos de Bolztman para k_B T = 2.5 J: \n', pn_x_b)
rho_beta_x_b = Gibbs_state(En_x, Psin_x, beta)
print('Hx: estado térmico k_B T = 2.5 J: \n', rho_beta_x_b)
print('Hx: estado térmico k_B T = 2.5 J (exp H): \n', expm(-beta * Hx) / np.trace(expm(-beta * Hx)))
l_Hx_b = np.linalg.eigvals(rho_beta_x_b)
print('Hx: pureza T =  2.5J: \n', (l_Hx_b**2).sum())


Hz: pesos de Bolztman para k_B T = 2.5 J: 
 [0.68997448 0.31002552]
Hz: estado térmico k_B T = 2.5J: 
 [[0.68997448 0.        ]
 [0.         0.31002552]]
Hz: estado térmico k_B T = 2.5J (exp H): 
 [[ 0.68997448 -0.        ]
 [-0.          0.31002552]]
Hz: pureza T =  2.5J: 
 0.5721806069594112

Hx: pesos de Bolztman para k_B T = 2.5 J: 
 [0.59868766 0.40131234]
Hx: estado térmico k_B T = 2.5 J: 
 [[ 0.5        -0.09868766]
 [-0.09868766  0.5       ]]
Hx: estado térmico k_B T = 2.5 J (exp H): 
 [[ 0.5        -0.09868766]
 [-0.09868766  0.5       ]]
Hx: pureza T =  2.5J: 
 0.5194785085169414
